[project]
name = "BrownianMotion"
namespace = "BrownianMotion"

[[modules]]
name = "BrownianMotion.Auxiliary.Adapted"

[[modules]]
name = "BrownianMotion.Auxiliary.Algebra"

[[modules]]
name = "BrownianMotion.Auxiliary.Analysis"

[[modules]]
name = "BrownianMotion.Auxiliary.ContinuousBilinForm"

[[modules]]
name = "BrownianMotion.Auxiliary.ENNReal"

[[modules]]
name = "BrownianMotion.Auxiliary.Filtration"

[[modules]]
name = "BrownianMotion.Auxiliary.FiniteInf"

[[modules]]
name = "BrownianMotion.Auxiliary.HasGaussianLaw"

[[modules]]
name = "BrownianMotion.Auxiliary.HasLaw"

[[modules]]
name = "BrownianMotion.Auxiliary.IsStoppingTime"

[[modules]]
name = "BrownianMotion.Auxiliary.Jensen"

[[modules]]
name = "BrownianMotion.Auxiliary.LinearAlgebra"

[[modules]]
name = "BrownianMotion.Auxiliary.Martingale"

[[modules]]
name = "BrownianMotion.Auxiliary.MeanInequalities"

[[modules]]
name = "BrownianMotion.Auxiliary.MeasureTheory"

[[modules]]
name = "BrownianMotion.Auxiliary.Metric"

[[modules]]
name = "BrownianMotion.Auxiliary.NNReal"

[[modules]]
name = "BrownianMotion.Auxiliary.Nat"

[[modules]]
name = "BrownianMotion.Auxiliary.Real"

[[modules]]
name = "BrownianMotion.Auxiliary.SetAlgebra"

[[modules]]
name = "BrownianMotion.Auxiliary.StoppedProcess"

[[modules]]
name = "BrownianMotion.Auxiliary.Topology"

[[modules]]
name = "BrownianMotion.Auxiliary.WithLp"

[[modules]]
name = "BrownianMotion.Auxiliary.WithTop"

[[modules]]
name = "BrownianMotion.Choquet.AnalyticSet"

[[modules]]
name = "BrownianMotion.Choquet.Capacity"

[[modules]]
name = "BrownianMotion.Choquet.CompactSystem"

[[modules]]
name = "BrownianMotion.Continuity.Chaining"

[[modules]]
name = "BrownianMotion.Continuity.CoveringNumber"

[[modules]]
name = "BrownianMotion.Continuity.HasBoundedInternalCoveringNumber"

[[modules]]
name = "BrownianMotion.Continuity.IsKolmogorovProcess"

[[modules]]
name = "BrownianMotion.Continuity.KolmogorovChentsov"

[[modules]]
name = "BrownianMotion.Continuity.KolmogorovChentsovInequality"

[[modules]]
name = "BrownianMotion.Debut.Approximation"

[[modules]]
name = "BrownianMotion.Debut.Basic"

[[modules]]
name = "BrownianMotion.Gaussian.BrownianMotion"

[[modules]]
name = "BrownianMotion.Gaussian.CovMatrix"

[[modules]]
name = "BrownianMotion.Gaussian.Gaussian"

[[modules]]
name = "BrownianMotion.Gaussian.GaussianProcess"

[[modules]]
name = "BrownianMotion.Gaussian.Moment"

[[modules]]
name = "BrownianMotion.Gaussian.MultivariateGaussian"

[[modules]]
name = "BrownianMotion.Gaussian.ProjectiveLimit"

[[modules]]
name = "BrownianMotion.Gaussian.StochasticProcesses"

[[modules]]
name = "BrownianMotion.StochasticIntegral.ApproxSeq"

[[modules]]
name = "BrownianMotion.StochasticIntegral.Cadlag"

[[modules]]
name = "BrownianMotion.StochasticIntegral.Centering"

[[modules]]
name = "BrownianMotion.StochasticIntegral.ClassD"

[[modules]]
name = "BrownianMotion.StochasticIntegral.DoobLp"

[[modules]]
name = "BrownianMotion.StochasticIntegral.DoobMeyer"

[[modules]]
name = "BrownianMotion.StochasticIntegral.Komlos"

[[modules]]
name = "BrownianMotion.StochasticIntegral.L2M"

[[modules]]
name = "BrownianMotion.StochasticIntegral.LocalMartingale"

[[modules]]
name = "BrownianMotion.StochasticIntegral.LocalMonad"

[[modules]]
name = "BrownianMotion.StochasticIntegral.LocalizingSequence"

[[modules]]
name = "BrownianMotion.StochasticIntegral.Locally"

[[modules]]
name = "BrownianMotion.StochasticIntegral.MathlibImports"

[[modules]]
name = "BrownianMotion.StochasticIntegral.OptionalSampling"

[[modules]]
name = "BrownianMotion.StochasticIntegral.Predictable"

[[modules]]
name = "BrownianMotion.StochasticIntegral.QuadraticVariation"

[[modules]]
name = "BrownianMotion.StochasticIntegral.SimpleProcess"

[[modules]]
name = "BrownianMotion.StochasticIntegral.SquareIntegrable"

[[modules]]
name = "BrownianMotion.StochasticIntegral.UniformIntegrable"

[atlas]
root = "../lean-atlas-for-brownian-motion"
